### ISSUE TITLE
Ruby 2.6.1 installation on WSL - permission denied

### ISSUE THREAD

**Issue by natr104** [learn-co-curriculum/wsl2-env-ruby#5]
![ruby error](https://user-images.githubusercontent.com/93766553/152663410-abfb52c5-22d0-4070-8436-ba5aee62d57c.png)

I was unable to install Ruby 2.6.1 in Ubuntu on Windows 10 as I received an "cannot create directory: Permission denied" error during installation. I resolved this problem by changing ownership of the rvm directory to my own user group as follows:

`cd /usr/share/rvm`
`sudo chown -Rv root:$USER .`

I noticed that by default the rvm directory is owned by "rvm", and the `rvm install 2.6.1` command from the installation instructions does not run with superuser permission and it does not work with `sudo`. After changing ownership the `rvm install 2.6.1` command and installation process completed successfully.

**Comment by lizbur10** [comment]
Hi @natr104! Thanks for bringing this to our attention. It looks as if you are working from an older version of the environment setup instructions. The current version has a troubleshooting section that includes that fix: https://github.com/learn-co-curriculum/phase-0-wsl2-env-ruby

Can you please provide the link to the Canvas page for me so I can fix it?

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by lizbur10** [comment]
Hi again @natr104 ! I'm going to go ahead and close this issue. Feel free to reopen it if you think a correction is still necessary. Thanks! 💙
